spring:
  test1:
    datasource:
      hikari:
        jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/test1
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        username: test1
        password: test1!
