jasypt:
  encryptor:
    password: "test"
    algorithm: "PBEWITHHMACSHA512ANDAES_256"
    key-obtention-iterations: 1000
    pool-size: 1
    provider-name: "SunJCE"
    salt-generator-classname: "org.jasypt.salt.RandomSaltGenerator"
    iv-generator-classname: "org.jasypt.iv.RandomIvGenerator"
    string-output-type: "base64"
    proxy-property-sources: false
#    skip-property-sources:
#      -